name: C++ Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        working-directory: q01
        run: g++ -std=c++23 -O2 -Wall -Wextra main.cpp -o app

      - name: Run program
        working-directory: q01
        run: ./app > output.txt

      - name: Compare with expected
        working-directory: q01
        run: diff -u expected.txt output.txt
